---

- name: Install required packages
  apt:
    pkg:
      - python-setuptools
      - python-virtualenv
      - python-dev
      - libxslt1-dev
      - gcc
      - libffi-dev
      - libjpeg-dev
      - libxml2-dev
      - libxslt-dev
      - libyaml-dev
      - libpq-dev
      - redis-server
      - postgresql-contrib
      - python-pexpect
    state: latest

- name: Start & enable redis
  systemd:
    name: "redis.service"
    state: started
    enabled: true

- name: Create sentry group
  group:
    name: sentry
    state: present

- name: create sentry user
  user:
    name: sentry
    group: sentry
    create_home: true

- name: Install citext postgresql extension
  become: true
  become_user: postgres
  postgresql_ext:
    name: citext
    db: sentry

- name: Install sentry
  pip:
    name:
      - sentry
      - sentry-plugins
    state: latest
    virtualenv: /opt/sentry
    virtualenv_python: python2
  notify: Restart Sentry
  register: sentry_install

- name: Sentry init
  command: /opt/sentry/bin/sentry init /etc/sentry
  args:
    creates: /etc/sentry
  register: sentry_init

- name: Configuration
  template:
    src: "etc/sentry/{{ item }}.j2"
    dest: "/etc/sentry/{{ item }}"
  with_items:
    - config.yml
    - sentry.conf.py
  notify: Restart Sentry

- name: Sentry migration
  command: /opt/sentry/bin/sentry upgrade --noinput
  environment:
    SENTRY_CONF: /etc/sentry
  when: sentry_install is changed

- name: Setup sentry systemd services
  template:
    src: "etc/systemd/system/sentry-{{ item }}.service.j2"
    dest: "/etc/systemd/system/sentry-{{ item }}.service"
  with_items:
    - web
    - worker
    - cron
  notify: Restart Sentry

- name: Start and enable sentry systemd services
  tags:
    - travis-exempt
  systemd:
    name: "sentry-{{ item }}.service"
    state: started
    enabled: true
  with_items:
    - web
    - worker
    - cron

- name: Sentry cleanup cron
  cron:
    user: sentry
    name: Sentry cleanup
    job: SENTRY_CONF=/etc/sentry /opt/sentry/bin/sentry cleanup --days=30 --silent --loglevel ERROR
    special_time: daily

- name: Create first sentry user
  command: "/opt/sentry/bin/sentry createuser --email {{ sentry_user.email }} --password {{ sentry_user.password }} --superuser"
  environment:
    SENTRY_CONF: /etc/sentry
  when: sentry_init is changed and sentry_user is defined
